name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-11
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Run tests
      run: swift test -v
